// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vblpmbxrubdptednjqbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibHBtYnhydWJkcHRlZG5qcWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTM4NTEsImV4cCI6MjA2NTk4OTg1MX0.0cEN2IXB8qbDBwlRcYKJfTF50E3Vlp8JsZQM87Dju54";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);